
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Red
    volumes:
      - .:/var/www
    working_dir: /var/www
    ports:
      - 9000:9000
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: Dasavena_TI_nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8
    container_name: Red_mysql 
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
        - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
